package mage.client.dialog;

import mage.constants.MultiplayerAttackOption;
import mage.constants.RangeOfInfluence;
import mage.game.match.MatchOptions;
import mage.game.mulligan.MulliganType;
import org.apache.log4j.Logger;

import javax.swing.*;

/**
 * App GUI: custom options for match/tournament
 *
 * @author artemiswkearney
 */
public class CustomOptionsDialog extends MageDialog {

    public enum SaveLoadKeys {
        TABLE(
                PreferencesDialog.KEY_NEW_TABLE_NUMBER_OF_FREE_MULLIGANS,
                PreferencesDialog.KEY_NEW_TABLE_NUMBER_OF_LIFE_AT_START,
                PreferencesDialog.KEY_NEW_TABLE_NUMBER_OF_HAND_SIZE_AT_START,
                PreferencesDialog.KEY_NEW_TABLE_MULLIGAN_TYPE,
                PreferencesDialog.KEY_NEW_TABLE_PLANECHASE
        ),

        TOURNEY(
                PreferencesDialog.KEY_NEW_TOURNAMENT_NUMBER_OF_FREE_MULLIGANS,
                PreferencesDialog.KEY_NEW_TOURNAMENT_NUMBER_OF_LIFE_AT_START,
                PreferencesDialog.KEY_NEW_TOURNAMENT_NUMBER_OF_HAND_SIZE_AT_START,
                PreferencesDialog.KEY_NEW_TOURNAMENT_MULLIGUN_TYPE,
                PreferencesDialog.KEY_NEW_TOURNAMENT_PLANE_CHASE
        );
        public final String NUMBER_OF_FREE_MULLIGANS;
        public final String NUMBER_OF_LIFE_AT_START;
        public final String NUMBER_OF_HAND_SIZE_AT_START;
        public final String MULLIGAN_TYPE;
        public final String PLANECHASE;

        SaveLoadKeys(String numberOfFreeMulligans, String startLife, String startHandSize, String mulliganType, String planechase) {
            NUMBER_OF_FREE_MULLIGANS = numberOfFreeMulligans;
            NUMBER_OF_LIFE_AT_START = startLife;
            NUMBER_OF_HAND_SIZE_AT_START = startHandSize;
            MULLIGAN_TYPE = mulliganType;
            PLANECHASE = planechase;
        }
    }

    private static final Logger logger = Logger.getLogger(CustomOptionsDialog.class);
    private final SaveLoadKeys saveLoadKeys;
    private final JButton openButton;

    /**
     * Creates new form NewTableDialog
     */
    public CustomOptionsDialog(SaveLoadKeys saveLoadKeys, JButton openButton) {
        this.saveLoadKeys = saveLoadKeys;
        this.openButton = openButton;
        initComponents();
        this.spnFreeMulligans.setModel(new SpinnerNumberModel(0, 0, 5, 1));
        this.chkCustomStartLife.setModel(new DefaultButtonModel());
        this.spnStartLife.setModel(new SpinnerNumberModel(20, 0, 100, 1));
        this.spnStartLife.setEnabled(false);;
        this.chkCustomHandSize.setModel(new DefaultButtonModel());
        this.spnStartHandSize.setModel(new SpinnerNumberModel(7, 0, 20, 1));
        this.spnStartHandSize.setEnabled(false);
        cbMulliganType.setModel(new DefaultComboBoxModel(MulliganType.values()));
        this.setModal(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGeneralOptions = new javax.swing.JLabel();
        lblMulliganType = new javax.swing.JLabel();
        cbMulliganType = new javax.swing.JComboBox<>();
        lblFreeMulligans = new javax.swing.JLabel();
        spnFreeMulligans = new javax.swing.JSpinner();
        jSeparator2 = new javax.swing.JSeparator();
        lblVariantOptions = new javax.swing.JLabel();
        chkPlaneChase = new javax.swing.JCheckBox();
        jSeparator4 = new javax.swing.JSeparator();
        btnOK = new javax.swing.JButton();
        chkCustomStartLife = new javax.swing.JCheckBox();
        chkCustomHandSize = new javax.swing.JCheckBox();
        spnStartHandSize = new javax.swing.JSpinner();
        spnStartLife = new javax.swing.JSpinner();

        setTitle("Custom Options");

        lblGeneralOptions.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblGeneralOptions.setText("General Options");

        lblMulliganType.setLabelFor(cbMulliganType);
        lblMulliganType.setText("Mulligan type:");
        lblMulliganType.setToolTipText("What style of mulligan?");

        cbMulliganType.setToolTipText("Selections the type of mulligan for games.");
        cbMulliganType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMulliganTypeActionPerformed(evt);
            }
        });

        lblFreeMulligans.setLabelFor(cbMulliganType);
        lblFreeMulligans.setText("Free mulligans:");
        lblFreeMulligans.setToolTipText("What style of mulligan?");

        spnFreeMulligans.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnFreeMulligansStateChanged(evt);
            }
        });

        lblVariantOptions.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblVariantOptions.setText("Variant Options");

        chkPlaneChase.setText("PlaneChase");
        chkPlaneChase.setToolTipText("Use the PlaneChase variant for your game.");
        chkPlaneChase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPlaneChaseActionPerformed(evt);
            }
        });

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        chkCustomStartLife.setText("Custom Start Life");
        chkCustomStartLife.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        chkCustomStartLife.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCustomStartLifeActionPerformed(evt);
            }
        });

        chkCustomHandSize.setText("Custom Start Hand Size");
        chkCustomHandSize.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        chkCustomHandSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCustomHandSizeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMulliganType)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbMulliganType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFreeMulligans)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnFreeMulligans))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnOK))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkPlaneChase)
                            .addComponent(lblGeneralOptions)
                            .addComponent(lblVariantOptions)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkCustomHandSize)
                                    .addComponent(chkCustomStartLife))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spnStartHandSize, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spnStartLife, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGeneralOptions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMulliganType)
                    .addComponent(cbMulliganType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnFreeMulligans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFreeMulligans))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkCustomStartLife)
                    .addComponent(spnStartLife, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkCustomHandSize)
                    .addComponent(spnStartHandSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVariantOptions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkPlaneChase)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        lblMulliganType.getAccessibleContext().setAccessibleName("Mulligan Type:");
        lblMulliganType.getAccessibleContext().setAccessibleParent(lblGeneralOptions);
        cbMulliganType.getAccessibleContext().setAccessibleName("");
        cbMulliganType.getAccessibleContext().setAccessibleDescription("Select the type of mulligan for games.");
        cbMulliganType.getAccessibleContext().setAccessibleParent(lblMulliganType);
        lblFreeMulligans.getAccessibleContext().setAccessibleDescription("");
        lblFreeMulligans.getAccessibleContext().setAccessibleParent(lblGeneralOptions);
        spnFreeMulligans.getAccessibleContext().setAccessibleDescription("Select the number of free mulligans");
        spnFreeMulligans.getAccessibleContext().setAccessibleParent(lblFreeMulligans);
        chkPlaneChase.getAccessibleContext().setAccessibleParent(lblVariantOptions);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPreviousConfigurationActionPerformed(java.awt.event.ActionEvent evt, int i) {//GEN-FIRST:event_btnPreviousConfigurationActionPerformed
    }//GEN-LAST:event_btnPreviousConfigurationActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        this.hideDialog();
    }//GEN-LAST:event_btnOKActionPerformed

    private void cbMulliganTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMulliganTypeActionPerformed
        updateActiveCount();
    }//GEN-LAST:event_cbMulliganTypeActionPerformed

    private void spnFreeMulligansStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnFreeMulligansStateChanged
        updateActiveCount();
    }//GEN-LAST:event_spnFreeMulligansStateChanged

    private void chkPlaneChaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPlaneChaseActionPerformed
        updateActiveCount();
    }//GEN-LAST:event_chkPlaneChaseActionPerformed

    private void chkCustomHandSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCustomHandSizeActionPerformed
        updateActiveCount();
    }//GEN-LAST:event_chkCustomHandSizeActionPerformed

    private void chkCustomStartLifeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCustomStartLifeActionPerformed
        updateActiveCount();
    }//GEN-LAST:event_chkCustomStartLifeActionPerformed

    public void showDialog() {
        this.setLocation(150, 100);
        this.setVisible(true);
    }

    public void onLoadSettings(int version) {

        String versionStr = "";
        switch (version) {
            case -1:
                versionStr = "-1"; // default (empty)
                break;
            case 1:
                versionStr = "1";
                break;
            case 2:
                versionStr = "2";
                break;
            default:
                versionStr = "";
                break;
        }

        this.chkPlaneChase.setSelected(PreferencesDialog.getCachedValue(saveLoadKeys.PLANECHASE + versionStr, "No").equals("Yes"));
        this.spnFreeMulligans.setValue(Integer.parseInt(PreferencesDialog.getCachedValue(saveLoadKeys.NUMBER_OF_FREE_MULLIGANS + versionStr, "0")));
        this.cbMulliganType.setSelectedItem(MulliganType.valueByName(PreferencesDialog.getCachedValue(saveLoadKeys.MULLIGAN_TYPE + versionStr, MulliganType.GAME_DEFAULT.toString())));
        Integer startLife = Integer.parseInt(PreferencesDialog.getCachedValue(saveLoadKeys.NUMBER_OF_LIFE_AT_START + versionStr, "" + Integer.MIN_VALUE));
        this.chkCustomStartLife.setSelected(startLife > Integer.MIN_VALUE);
        this.spnStartLife.setValue(startLife > Integer.MIN_VALUE ? startLife : 20);
        Integer startHandSize = Integer.parseInt(PreferencesDialog.getCachedValue(saveLoadKeys.NUMBER_OF_HAND_SIZE_AT_START + versionStr, "" + Integer.MIN_VALUE));
        this.chkCustomHandSize.setSelected(startHandSize >= 0);
        this.spnStartHandSize.setValue(startHandSize >= 0 ? startHandSize : 7);

        updateActiveCount();
    }

    public void onSaveSettings(int version, MatchOptions options) {
        String versionStr = "";
        switch (version) {
            case 1:
                versionStr = "1";
                break;
            case 2:
                versionStr = "2";
                break;
            default:
                versionStr = "";
                break;
        }
        PreferencesDialog.saveValue(saveLoadKeys.NUMBER_OF_FREE_MULLIGANS + versionStr, Integer.toString(options.getFreeMulligans()));
        PreferencesDialog.saveValue(saveLoadKeys.MULLIGAN_TYPE + versionStr, options.getMulliganType().toString());
        Integer startLife = options.getStartLife();
        PreferencesDialog.saveValue(saveLoadKeys.NUMBER_OF_LIFE_AT_START + versionStr, startLife == null ? null : Integer.toString(startLife));
        Integer startHandSize = options.getStartHandSize();
        PreferencesDialog.saveValue(saveLoadKeys.NUMBER_OF_HAND_SIZE_AT_START + versionStr, startHandSize == null ? null : Integer.toString(startHandSize));
        PreferencesDialog.saveValue(saveLoadKeys.PLANECHASE + versionStr, options.isPlaneChase() ? "Yes" : "No");
    }

    /**
     * Applies this dialog's configured match options to a MatchOptions object.
     */
    public void writeMatchOptionsTo(MatchOptions options) {
        options.setFreeMulligans((Integer) spnFreeMulligans.getValue());
        options.setStartLife(chkCustomStartLife.isEnabled() ? (Integer) spnStartLife.getValue() : null);
        options.setStartHandSize(chkCustomHandSize.isEnabled() ? (Integer) spnStartHandSize.getValue() : null);
        options.setMullgianType((MulliganType) cbMulliganType.getSelectedItem());
        options.setPlaneChase(chkPlaneChase.isSelected());
    }

    public void updateActiveCount() {
        int activeCount = 0;
        if ((Integer)spnFreeMulligans.getValue() > 0) activeCount++;
        if (chkCustomStartLife.isEnabled()) activeCount++;
        spnStartLife.setEnabled(chkCustomStartLife.isEnabled());
        if (chkCustomHandSize.isEnabled()) activeCount++;
        spnStartHandSize.setEnabled(chkCustomHandSize.isEnabled());
        if (!cbMulliganType.getSelectedItem().toString().equals(MulliganType.GAME_DEFAULT.toString())) activeCount++;
        if (chkPlaneChase.isSelected()) activeCount++;
        if (activeCount == 0) {
            openButton.setText("Custom Options...");
        }
        else {
            openButton.setText("Custom Options (" + activeCount + ")");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JComboBox<String> cbMulliganType;
    private javax.swing.JCheckBox chkCustomHandSize;
    private javax.swing.JCheckBox chkCustomStartLife;
    private javax.swing.JCheckBox chkPlaneChase;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblFreeMulligans;
    private javax.swing.JLabel lblGeneralOptions;
    private javax.swing.JLabel lblMulliganType;
    private javax.swing.JLabel lblVariantOptions;
    private javax.swing.JSpinner spnFreeMulligans;
    private javax.swing.JSpinner spnStartHandSize;
    private javax.swing.JSpinner spnStartLife;
    // End of variables declaration//GEN-END:variables
}
